### ISSUE TITLE
[Idea] Free tier tools & services

### ISSUE THREAD

**Issue by Ampsicora** [kamranahmedse/roadmap.sh#101]
### What roadmap is this issue about?
- [ ] All Roadmaps

### What is this issue about?

- [ ] Sharing an Idea

## Description

On [this repo](https://github.com/ripienaar/free-for-dev) there are a lot of useful free tier tools and services that can be integrated, just link them on a properly way or link the website ( [free-for.dev](https://free-for.dev) ) on each roadmap could be useful for many people

**Comment by kamranahmedse** [comment]
That's a good idea. We may add that later when we will add the resources. Thank you!
