### ISSUE TITLE
[Frontend Developer] - Move CSS-Preprocessors after build step

### ISSUE THREAD

**Issue by davidbernegger** [kamranahmedse/roadmap.sh#11]
CSS (Pre)-Processors might be better placed after build tools as tools like postcss / sass / less etc. require an actual build step for any real usage 

![image](https://user-images.githubusercontent.com/16232537/69326031-6b453680-0c4b-11ea-9fb8-2d5cca42a369.png)

**Comment by kamranahmedse** [comment]
This has been fixed. Thank you for reporting.
