### ISSUE TITLE
Making Roadmaps Interactive

### ISSUE THREAD

**Issue by timkleier** [kamranahmedse/roadmap.sh#116]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [x] All Roadmaps

#### What is this issue about?

- [x] Functionality of the website
- [x] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [x] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

I'd like to discuss making these roadmaps interactive, such as getting a basic definition of a resource and potentially links for getting started with a given technology. [See the HTML example below with the sidebar display.]

![image](https://user-images.githubusercontent.com/1045616/73045977-64929580-3e2d-11ea-88c4-06863616111a.png)

If you think it would make a valuable addition to your site, I'd love to brainstorm with you how best to integrate something like this into roadmap.sh. To indicate my interest level, I'm about halfway through the process of programmatically converting Balsamiq's JSON output of the Front-end Roadmap to SVGs for easier JS interactivity.

**Comment by kamranahmedse** [comment]
@timkleier thank you for the suggestion. Yes, it definitely is in our plan. I had a call with the CEO of Balsamiq Peldi earlier this week – they will be adding the SVG exports in the coming days. Once it is introduced, we were planning a similar format as you suggested in your mockup. We will hopefully not have to go through this hassle of converting Balsamiq JSON to SVG manually. 

Having said that, before my call with Balsamiq I was almost finishing something for the interactivity. It would allow easier drag/drop and addition of the nodes for the contributions and allow us to have detailed popups and progress tracking for the people following the roadmaps.

![snapper-3](https://user-images.githubusercontent.com/4921183/73087986-31b3d480-3ef5-11ea-8d3d-affbf623dac5.gif)

What do you think? Happy to get your feedback.

**Comment by timkleier** [comment]
@kamranahmedse, that’s great to hear that Balsamiq is going to provide SVG exports. But I like the direction you’re going with drag and drop interactivity and the ability to add nodes through the interface.

I’ll probably reach out via email, but I’d like to see how our visions align and maybe I could join this project somehow.
