### ISSUE TITLE
[DevOps Roadmap] - Add Prometheus and Grafana to Infrastructure Monitoring

### ISSUE THREAD

**Issue by adampie** [kamranahmedse/roadmap.sh#12]
Might be worth mentioning Prometheus and Grafana under Infrastructure Monitoring.

- [Prometheus](https://prometheus.io/)
- [Grafana](https://grafana.com/)

Both are open source and quite commonly used.

**Comment by Aytuar** [comment]
+ I vote for that.

**Comment by wbh1** [comment]
OpenTracing/Jaegar are worth mentioning in "Application Monitoring", too. They fit into the "tracing" pillar of observability that I think we're trying to encompass in that section.

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
