### ISSUE TITLE
Windows: error while starting dev locally

### ISSUE THREAD

**Issue by pybala** [kamranahmedse/roadmap.sh#130]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [x] All Roadmaps

#### What is this issue about?

- [x] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

First of all thanks to @kamranahmedse for this wonderful tool.

I'm trying to run in windows and I found some issues with dev run commands.
Set env in package.json is for Linux, started with "next" (NODE_ENV already set) and getting below error
![image](https://user-images.githubusercontent.com/9416267/74125186-8c8a4300-4bfa-11ea-925f-4fe9cecf00ff.png)

Thanks,
Bala

**Comment by mustafam-globant** [comment]
I am too facing same issue. Is it not configured to work in windows?
![image](https://user-images.githubusercontent.com/64200846/87156471-543a7e00-c2da-11ea-9aba-26ac5b24e013.png)

**Comment by kamranahmedse** [comment]
It should be fine now. Can you please try again?
