### ISSUE TITLE
Apache Kafka is not a Message Broker

### ISSUE THREAD

**Issue by riferrei** [kamranahmedse/roadmap.sh#156]
#### What roadmap is this issue about?

- [  ] Frontend Roadmap
- [x] Backend Roadmap
- [  ] DevOps Roadmap
- [  ] All Roadmaps

#### What is this issue about?

- [  ] Functionality of the website
- [  ] Discussion for a pull request I would want to open.
- [  ] Addition of a new item
- [  ] Removal of some existing item
- [x] Changing in arrangement
- [  ] General suggestion
- [x] Sharing an Idea
- [  ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

In nutshell, Apache Kafka is not a message broker but instead, it is a distributed streaming platform:

![image](https://user-images.githubusercontent.com/35476/79259029-0983a400-7e5a-11ea-943d-aa0252bafd8f.png)

Messaging and pub/sub semantics is only part of the scope of Kafka, focused in how its client APIs behave but in general Kafka is not meant to be used for messaging.

Thanks,

-- @riferrei

**Comment by sankethchebbi** [comment]
I will take this up and rectify it.

**Comment by sankethchebbi** [comment]
I looked it up. It also is a messaging broker.

**Comment by kamranahmedse** [comment]
Thank you for reporting @riferrei while I agree with you about the usecases, it doesn't mean that [putting it under the "Message Brokers"](https://en.wikipedia.org/wiki/Message_broker#List_of_message_broker_software) would be wrong. However, we will see how we can make it clear in the roadmap. Thank you!
