### ISSUE TITLE
[Frontend Developer] - Add Testing to Frontend Roadmap

### ISSUE THREAD

**Issue by geoffdavis92** [kamranahmedse/roadmap.sh#162]
#### What roadmap is this issue about?

- [x] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [x] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

JavaScript testing is currently not an item on the Frontend Developer roadmap, but it is a critical skill to learn and exercise, especially when creating applications using popular frontend libraries and frameworks.

Technologies like Mocha, Chai, Enzyme, QUnit, Jest, Cypress, and many others allow developers to test their code against technical and business constraints. This also allows developers to create robust new modules/components/interactivity using test-driven development, while mitigating risk of shipping bugs.

Please consider adding this skill track to the Frontend developer roadmap.

**Comment by kamranahmedse** [comment]
Thanks Geoff, for opening the issue. We do have testing in there:
 
![image](https://user-images.githubusercontent.com/4921183/80801290-e88eb300-8bbc-11ea-998a-a756110803e7.png)
