### ISSUE TITLE
[RequestRoadmap] - Systems Engineer

### ISSUE THREAD

**Issue by hereiskkb** [kamranahmedse/roadmap.sh#17]
It would be great if we could have a road-map for people willing to be system engineers, creating, modifying and maintaining operating systems, and related system applications.

**Comment by aimproxy** [comment]
I will suggest change the name of the request to `Embedded Systems Engineer` instead of  `Systems Engineer`, I this the job is bad labeled! 👍

**Comment by aimproxy** [comment]
I build a small list based [Tesla ](https://www.tesla.com/careers/search#/?keyword=embedded)
on offering jobs: 

## Languages
- [ ] C/C++

## Beneficial Knowledge Languages
- [ ] Go
- [ ] Python
- [ ] shell scripting

## Standards for software development
- [ ] MISRA C
- [ ] Mistray C

## Microcontrollers
- [ ] TI DSPs
- [ ] NXP

## Architectures
- [ ] ARM
- [ ] x86

## Embedded networking protocols 
- [ ] CAN
- [ ] RS-485
- [ ] ModBus
- [ ] Ethernet

## Security
- [ ] SELinux
- [ ] Crypto
- [ ] Verified boot

## Linux Commands
- [ ] make
- [ ] ls, cd, pwd
- [ ] man, info, apropos

**Comment by hereiskkb** [comment]
Thanks for listing. 
Sorry I couldn't get back to this sooner. Great job! Appreciate the effort!
