### ISSUE TITLE
[DevOps Roadmap] - Add Pulumi to Infrastructure Provisioning

### ISSUE THREAD

**Issue by c0bra** [kamranahmedse/roadmap.sh#18]
[Pulumi](https://www.pulumi.com) is a great tool for infrastructure as code that lets you use languages you already know (js and python, go and c# coming). It has feature parity with Terraform and offers some useful facades for common patterns.

**Comment by mhmdio** [comment]
+1

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
