### ISSUE TITLE
[Frontend Developer] - SSR react

### ISSUE THREAD

**Issue by sayjeyhi** [kamranahmedse/roadmap.sh#26]
Build SSR applications could be done with `express` too. And it is so popular, but here just next.js and after.js are listed

**Comment by kamranahmedse** [comment]
Hey, thank you for opening the issue - although possible, it isn't the most widely used option. 

Our goal is not to have the biggest list of everything available out there. It is to have the most in-demand options that are available today and next.js *is* the most in-demand if you compare it.
