### ISSUE TITLE
[RequestRoadmap] - RPC

### ISSUE THREAD

**Issue by brillout** [kamranahmedse/roadmap.sh#32]
Author of [Wildcard API](https://github.com/reframejs/wildcard-api) here.

REST and GraphQL are increasingly being replaced with RPC in the industry.

Many devS should be using RPC instead of GraphQL.

Let me know if you have questions.

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. This is rather going to be an addition to the backend roadmap than a separate roadmap. It is planned to be added to the backend roadmap in the coming release.
