### ISSUE TITLE
[RequestRoadmap] - Devops IT part from sysadmin

### ISSUE THREAD

**Issue by dcpc007** [kamranahmedse/roadmap.sh#38]
Hi, 

Maybe you could add a devops path from a sysadmin start.
I've seen many sysadmin switching to devops with a dev groups and take the 6 to 9 directly, with only more "basic" knowledge of programming

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. I have seen that at some organizations also; SysAdmins calling themselves "DevOps Engineers" while all they know is how to perform *some* of the operations tasks, while in actuality [DevOps is something completely different](https://www.atlassian.com/devops) - you need to be a good developer. 

Having said that in the next release we are going to divide the operations roadmap into different roles and positions and it would be a bit more clear.

**Comment by dcpc007** [comment]
On other side, many good developers thinks they are good at managing infrastructure and it's rarely the case :)
that's why for me devops is not only how developers can do more than dev ...but more the exchange (sorry don't find the good english term) between dev world and admin/ops works.
