### ISSUE TITLE
[Frontend Developer] - Add more static site generators

### ISSUE THREAD

**Issue by shiftgeist** [kamranahmedse/roadmap.sh#45]
There are more site generators, besides GatsbyJS, that also don't require javascript, but have a lot more performance, think hugo.

Would like to see these in the roadmap:

- [Hugo](https://github.com/gohugoio/hugo) (go) (~40k stars)
- [Nuxt](https://nuxtjs.org/) (vue) (~24k stars) 

This side is a great overview of what sidegenerators exist: https://www.staticgen.com/

**Comment by kamranahmedse** [comment]
This has been fixed. Thank you for reporting!
