### ISSUE TITLE
[DevOps Roadmap] - Serverless

### ISSUE THREAD

**Issue by ericpardee** [kamranahmedse/roadmap.sh#56]
I hate the term _serverless_, but this Roadmap is missing serverless, aka Function as a Service, FaaS

Things like
- AWS Lambda
- Azure Functions
- Google Cloud Functions
- Kubernetes Kubeless/Knative/OpenFaaS

For Deployment of serverless
- serverless framework
- terraform

**Comment by larrybolt** [comment]
Could this be seen as one of the skills of a cloud architect?

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏

**Comment by ericpardee** [comment]
I received an email about https://pages.awscloud.com/GLOBAL-partner-OE-Slalom-DevOps-Q2-Webinar-2020-reg-event.html and it reminded me about this. I went to https://roadmap.sh/devops but there's no mention of serverless. Not sure what happened, no linked pull requests.

**Comment by kamranahmedse** [comment]
@ericpardee it's there in the DevOps

![image](https://user-images.githubusercontent.com/4921183/79690646-7d63e900-826c-11ea-8382-f29a36351bfd.png)
