### ISSUE TITLE
[Backend Developer] - suggested documentation (official or unofficial)

### ISSUE THREAD

**Issue by younesZdDz** [kamranahmedse/roadmap.sh#60]
It would be an improvement and also helpful if you added links to suggest a good documentation for each step (official ones or not).

**Comment by kamranahmedse** [comment]
![image](https://user-images.githubusercontent.com/4921183/70411982-125c0780-1a6d-11ea-9b24-503e0726f37f.png)

It is already being worked upon and will be available in the next release.
