### ISSUE TITLE
(roadmap - devops) Node.js is not a programming language

### ISSUE THREAD

**Issue by ali-garajian** [kamranahmedse/roadmap.sh#66]
Hi,
Thanks a lot for creating this. 
I just wanted to point out that node.js is not a programming language, it is a runtime environment. The language would be any of the languages under the ECMA standard and their transpiles like Javascript and Typescript

**Comment by dudemelo** [comment]
We should also remove it from backend development.

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
