### ISSUE TITLE
Roadmap Legend not included

### ISSUE THREAD

**Issue by happyliltrees** [kamranahmedse/roadmap.sh#69]
Hi There!

I noticed that the [roadmap legend image](https://github.com/kamranahmedse/developer-roadmap/raw/master/images/intro.png) in the introduction section of @kamranahmedse 's original [developer-roadmap repo](https://github.com/kamranahmedse/developer-roadmap) is not included on the pages from Roadmap.SH. 

I was wondering if this was intentional? If not, would anyone have an issue with me opening a PR to include that image on the roadmap pages?  

Thanks!

**Comment by kamranahmedse** [comment]
Hey, I am aware of it - this will be fixed in the 2020 release which is soon to be published.

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
