### ISSUE TITLE
Web Accessibility (or UX) branch

### ISSUE THREAD

**Issue by thiagotpc** [kamranahmedse/roadmap.sh#75]
Nice job! 

I would suggest creating a branch to include "Web Accessibility" or "User Experience" on the Front-End roadmap. 

If opt for Web Accessibility, the topics would be:
- Use cases and rules;
- How to use screenreaders,
- WCAG;
- ARIA;

If opt for User Experience, the topics would be:
- Principles of Design on Design Layout;
- Navigation Design;
- Web Usability;
- Web Accessibility;
- User Testings;

I think that Web Accessibility is very important in context of coding web pages and web applications. And this is a responsibility of front-end rule.  

About the User Experience, I think that this additional skill will allow deliver interfaces with most quality.

**Comment by kamranahmedse** [comment]
Although not detailed, web Accessibility has now been mentioned in the roadmap. Regarding the detailed, I will see what we can do in the future. Thank you!
