### ISSUE TITLE
[DevOps Roadmap] - Add Gitlab to CI/CD

### ISSUE THREAD

**Issue by ksemaev** [kamranahmedse/roadmap.sh#81]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [x] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [x] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

Add Gitlab and Bamboo to CI/CD tools, they are used more often then Drone or Travis

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
