### ISSUE TITLE
[Frontend Developer] - Replace cssnext with postcss-preset-env

### ISSUE THREAD

**Issue by JessevanAssen** [kamranahmedse/roadmap.sh#82]
#### What roadmap is this issue about?

- [x] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [x] Addition of a new item
- [x] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here
[cssnext](https://cssnext.github.io/) has been deprecated in favor of [postcss-preset-env](http://preset-env.cssdb.org/).

This is indicated by a banner on the top when the [cssnext](https://cssnext.github.io/) website is visited. It links to [this blog post](https://moox.io/blog/deprecating-cssnext/) which gives some more details.

**Comment by dudemelo** [comment]
IMO we shouldn't add `postcss-preset-env` once it works as a PostCSS plugin and PostCSS is already on the list.

👍 to remove cssnext.

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
