### ISSUE TITLE
[Frontend Developer] - PNPM Package Manager

### ISSUE THREAD

**Issue by marciobarroso** [kamranahmedse/roadmap.sh#86]
#### What roadmap is this issue about?

- [X] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [X] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [X] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [X] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [X] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

I would like to suggest a new package manager called [PNPM](https://pnpm.js.org/)

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. Our goal is to not convolute the roadmap by mentioning every available option and are just focusing on what is the most in demand today. PNPM is good but npm and yarn the widely used ones so I don't think we should add pnpm.

Thank your for your suggestion though 🙏
