### ISSUE TITLE
[DevOps Roadmap] - Add SQL(postgresql, oracle)

### ISSUE THREAD

**Issue by oleg9301** [kamranahmedse/roadmap.sh#89]
#### What roadmap is this issue about?
* [ ]  Frontend Roadmap
* [ ]  Backend Roadmap
* [x]  DevOps Roadmap
* [ ]  All Roadmaps

#### What is this issue about?
* [ ]  Functionality of the website
* [ ]  Discussion for a pull request I would want to open.
* [x]  Addition of a new item
* [ ]  Removal of some existing item
* [ ]  Changing in arrangement
* [ ]  General suggestion
* [ ]  Sharing an Idea
* [ ]  Something else

#### Please acknowledge the below listed
* [x]  This is not a duplicate issue. I have searched and there is no existing issue for this.
* [x]  I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
* [x]  I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here
Add SQL(basic knowledge  for a middle level devops)
Add Postgresql, Oracle(junior DBA level knowledge for a middle level devops)

**Comment by kamranahmedse** [comment]
If you look at the intro section in the original roadmap, the DevOps roadmap is branching out of the backend roadmap which includes the SQL knowledge as you listed. That part is missing on the website and it will be fixed in the coming release. Thank you! 🙏
