### ISSUE TITLE
[Frontend Developer] - Replace "StandardJS" with more industry-standard linter config

### ISSUE THREAD

**Issue by ChemicalRascal** [kamranahmedse/roadmap.sh#93]
#### What roadmap is this issue about?

- [x] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [x] Addition of a new item
- [x] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

So, StandardJS is already greyed out, indicating (to my understanding) that it isn't recommended -- I think it'd be worth instead replacing it with one that is worth recommending.

The [Airbnb style guide/ESLint config](https://github.com/airbnb/javascript) (it's an ESLint config, promise) is generally suggested (and, helpfully, is not confusingly named) -- and notably is also a really, really solid, well-argued style guide.

There isn't, I would argue, enough room to list a whole lot of linter configs, but I'd suggest if it's worth listing one, it's worth listing one you can recommend. (And folks adopting the Airbnb style are, IMO, a lot less likely to be murdered by their future colleagues than those adopting the StandardJS style, ref [21.1](https://github.com/airbnb/javascript#semicolons--required). But there are other linter configs out there.)

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. I don't think there is any need for mentioning linting configurations in the roadmap — it would just result in the convolution.

**Comment by ChemicalRascal** [comment]
Sorry, Kamran, I believe I might not have been as clear as I should have been.

You're already mentioning a linter config on the roadmap -- that's what StandardJS is. I personally agree that it's not worth mentioning particular configs, but I supposed you listed one for the sake of an example.

Should I submit a PR removing the existing config?

**Comment by munizart** [comment]
@ChemicalRascal [`standard`](https://www.npmjs.com/package/standard) is a zero config linting for using [StandardJS](https://standardjs.com/) rules. Not to be confused with [`eslint-config-standard`](https://github.com/standard/eslint-config-standard).
It could be more clearer on roadmap? maybe, but just googling "StandardJS" (as is on roadmap) would lead you to the official website where `standard` is reccomended over `eslint-config-standard`.

Also, I can't see a reason it should be grayed out, as `standard` is a great start point for those that never used linters before. @kamranahmedse  is this open for debate or is something already settled?

**Comment by ChemicalRascal** [comment]
@munizart -- I would recommend giving a look at the actual repo of `standard`. `standard` is ultimately just a bundling of eslint and a config thereof. `eslint-config-standard` _is a dependency of_ `standard`. `standard` itself defines no rules, nor even code beyond metautilities to update itself -- the actual work is achieved by eslint and the config package.

What I've suggested above is that `standard` be replaced by the Airbnb config, as it is much closer to industry standard. However, given @kamranahmedse 's reply above I would suggest it would be more proper and in line with the goals of the roadmap to simply not list a particular style or config.

**Comment by munizart** [comment]
@ChemicalRascal i think your own preferences is getting in the way here, tbh. Both rule sets are pretty industry standard (airbnb has slight more npm downloads https://www.npmtrends.com/eslint-config-airbnb-vs-eslint-config-standard-vs-standard. `stats` are biased as `eslint-config-airbnb` lays in a monorepo with multiple packages).
And even tho `standard` depends upon `eslint-config-standard` it ofers its own cli, with opinionated zero-config linting. It's a linter by itself.
Saying it's just a packed config of `eslint` is true, but as true as `parcel` is a packed configuration of `webpack` and `babel`. Should `parcel` be removed from roadmap too?

**Comment by ChemicalRascal** [comment]
Perhaps it's worth considering, sure. I'm simply saying that if we don't want any linter configurations, let's not have any linter configurations. That Standard is a prepackaged config doesn't make it not an eslint config, no matter how it describes itself -- let us see it for what it is, not what it claims to be.

The prospect that Standard needed to be replaced in the first place stemmed from how it is already presented -- greyed, that is, not recommend. As stated in my opening post. I'm not sure why you believe I, personally, have biases against Standard.

I think you're reading too much into things and presuming preferences, and I'd strongly caution you against that. It's both inclined to sidetrack discussion, and rude.

**Comment by ChemicalRascal** [comment]
Furthermore, on more specific points -- double is not "slightly more". Airbnb is not only vastly more popular, as your link demonstrates, it is blatantly more in line with industry norms in content.

Standard still forbids semicolons. Airbnb mandates them. I'd be hard pressed to imagine any clearer indicator of which is more appropriate in a corporate or industry setting.
