### ISSUE TITLE
[Frontend Developer] - Progress bars and interactivity

### ISSUE THREAD

**Issue by KCerveny** [kamranahmedse/roadmap.sh#99]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [x] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [X] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here
Hello, 
I think that this is a **brilliant** tool for new developers like myself which are looking to learn new skills, and would like to see the "bigger picture" to give us some guidance in our journey of self-teaching these skills. 
One thing that I think would polish this off is intractability. Again, as someone who likes to see the big picture, it would be a cool feature to be able to "check" off skills that we have covered and think that we have a strong enough grasp of. In tandem, graying-out these completed tasks would make the incomplete skills more visually prominent, and would catch my gaze more easily. In addition, this functionality could be combined with a progress bar of sorts, which would even further improve the visibility of a learner's progress. 
I am not sure if these are feasible changes to make, but I think that this could really make a big difference. I think that these roadmaps are already a HUGE development for learning, as I have wished for something like this for a long time. 
Thanks for making this, and thank you for taking suggestions. 
> Kellan C.

**Comment by kamranahmedse** [comment]
Hey, thank you for the suggestion. It is already being worked upon and will be published in the next few weeks! :)

Here is how it roughly looks like:

![snapper-4](https://user-images.githubusercontent.com/4921183/72497283-8eecbd80-3845-11ea-8faa-2af8b501712b.gif)
